# Generated by Django 4.1.2 on 2023-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_city_alter_customuser_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='media/covers/')),
                ('pdf', models.FileField(upload_to='media/pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
