# Generated by Django 4.1.2 on 2023-02-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_uploaded_files_desc_uploaded_files_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='cover',
            field=models.ImageField(upload_to='media/covers'),
        ),
        migrations.AlterField(
            model_name='uploaded_files',
            name='pdf',
            field=models.FileField(upload_to='media/pdfs'),
        ),
    ]
