# Generated by Django 4.1.2 on 2023-02-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
