# Generated by Django 4.1.2 on 2023-02-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_user', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ccnumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cctype',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='expdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='public_visibility',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
