# Generated by Django 4.1.2 on 2023-02-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_user', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cvc',
            field=models.IntegerField(default=0),
        ),
    ]
