# Generated by Django 4.1.2 on 2023-02-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_user', '0006_alter_customuser_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
