# Generated by Django 4.1.2 on 2023-02-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_user', '0007_alter_customuser_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='public_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
