# Generated by Django 4.1.2 on 2023-02-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_expdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='credit_num',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ccnumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cctype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
