# Generated by Django 4.1.2 on 2023-02-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_uploaded_files_cover_alter_uploaded_files_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='cover',
            field=models.ImageField(upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='uploaded_files',
            name='pdf',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
