# Generated by Django 4.1.2 on 2023-02-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_uploaded_files_cover_alter_uploaded_files_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cctype',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='uploaded_files',
            name='category',
            field=models.CharField(max_length=250),
        ),
    ]
